### ISSUE TITLE
prepare enabling participation as PR

### ISSUE THREAD

**Issue by brenzi** [integritee-network/crowdloan#32]
Currently, master is the version where basically all Kusama interaction read/write is disabled. The following stage should be prepared as PR's to master and they will only be merged once CI passes.

PR: enable participation

to be merged after registering crowdloan and testing a contribution with local deployment

**Comment by Alirazadar** [comment]
Can we have a quick call about this during the week? Thank you!

**Comment by brenzi** [comment]
fixed by #34
