### ISSUE TITLE
launch Kusama api in background

### ISSUE THREAD

**Issue by brenzi** [integritee-network/crowdloan#33]
Currently, we first connect to Kusama before the page loads. This feels slow and unnecessary

Could we load the page first and just show a "loading" animation for the content where we need Kusama connection (amount raised, leaderboard, participate)

This would at the same time resolve the issue of the slow-load for the leaderboard and we could go back to loading all pages

**Comment by brenzi** [comment]
@Alirazadar do you have an idea how we could do this to accelerate the page loading?

**Comment by mosonyi** [comment]
Only the over the KSM amount should be a "loader" not on the entire page.

**Comment by mosonyi** [comment]
I have checked it. Perfect.
