### ISSUE TITLE
implement referral program

### ISSUE THREAD

**Issue by brenzi** [integritee-network/crowdloan#37]
<html><body>
<h2 id="Requirements:" data-renderer-start-pos="493">Requirements:<span role="presentation" class="heading-anchor-wrapper"></span></h2><p data-renderer-start-pos="508"><strong data-renderer-mark="true">Step 1</strong>: If someone wants to get a referral code they have to bond a minimum amount of KSM (0.1 for example). </p><ul class="ak-ul" data-indent-level="1"><li><p data-renderer-start-pos="621">They enter their wallet address in order to bond the KSM - this means we can easily link wallet addresses and referral codes in the DB.</p></li><li><p data-renderer-start-pos="760">If they want a referral code they enter their email address and a referral code is generated and sent to them via email. This way we also obtain their contact info in case we want to leverage people who are able to mobilise a lot of other contributors as ambassadors for example.</p></li></ul><p data-renderer-start-pos="1043">They now have a referral code they can share and have bonded a small amount of KSM to the project.</p><p data-renderer-start-pos="1143"> </p><p data-renderer-start-pos="1145"><strong data-renderer-mark="true">Step 2: </strong>If someone has received a referral code then they can enter it in the first instance (see Step 1) when they choose to Bond KSM. </p><ul class="ak-ul" data-indent-level="1"><li><p data-renderer-start-pos="1285">They enter their wallet details and the referral code. Again this is another datapoint in the DB that we then collect.</p></li><li><p data-renderer-start-pos="1407">Equally if they want their own referral code they can follow the same procedure as outlined in Step 1.</p></li></ul><p data-renderer-start-pos="1513"> </p><p data-renderer-start-pos="1515"><strong data-renderer-mark="true">Database:</strong></p><p data-renderer-start-pos="1526">In order for this to function we need to store the details so that we can assign the bonuses once the crowdloan campaign has closed. This does not have to be complex and we only need a few data points for this to work effectively.</p><div style="left: -3px;" class="sc-kpOJdX dEeRhR"></div><div class="pm-table-container  sc-jKJlTe loXQau" data-layout="wide" style="width: 766px; left: -3px;"><div class="pm-table-wrapper">

Wallet Address | Referral Code 1 | Referral Code 2 | Contribution | Email address
-- | -- | -- | -- | --
  | This is the referral code they may have used that they got from someone else | This is their own referral code | Their KSM contribution amount |  

</div></div><p data-renderer-start-pos="2009"> </p><p data-renderer-start-pos="2011">As such this can easily be integrated into the existing Crowdloan page but has the potential to signficantly boost the KSM contributions. We have had a lot of queries about this from people who have their own large followings and communities that they would like to mobilise. </p><p data-renderer-start-pos="2289"> </p><p data-renderer-start-pos="2291"><strong data-renderer-mark="true">T&amp;C’s:</strong></p><p data-renderer-start-pos="2299">We will also need to include a page detailing the T&amp;C’s for the referral program (i.e. how much they get, when they get it, that they can only get it through the integritee crowdloan page etc.). This content can easily be drafted by us and only has to be a static page. Although for easy access we could also include a few FAQs around the referral program on the Crowdloan page.</p>
</body>
</html>

**Comment by brenzi** [comment]
We have to offer some way of obtaining a referral key for those who have contributed before the start of the referral program. Maybe we could ask them to make another tiny contribution to obtain the key and then the entire contribution will be considered for the referral bonus

**Comment by Alirazadar** [comment]
@brenzi can we have a short call regarding this issue? I could not really understand these points.

**Comment by brenzi** [comment]
closing in favor of #39,#40,#41
