### ISSUE TITLE
setup webserver with mysql to host crowdloan page

### ISSUE THREAD

**Issue by brenzi** [integritee-network/crowdloan#42]
We can no longer use gh-pages. need a stateful setup now

I suggest a LAMP setup on DO.

we'll need yarn too and automate deployment with GH hooks from the crowdloan repo (trggered by release)

**Comment by mosonyi** [comment]
@brenzi please review 

https://integritee.atlassian.net/wiki/spaces/INTEGRITEE/pages/238518515/Crowdloan+API+Deployment+Usage#Usage
