### ISSUE TITLE
send txhash to db backend, not blockhash

### ISSUE THREAD

**Issue by brenzi** [integritee-network/crowdloan#49]
Here we get the txhash
https://github.com/integritee-network/crowdloan/blob/6cc3798978dddb4120d55d8130db3bb52e0ddcbe/src/substrate-lib/components/TxButton.js#L228

`unsub` stores the tx-hash. See https://polkadot.js.org/docs/api/start/api.tx

currently, we return the block hash that includes the tx:
https://github.com/integritee-network/crowdloan/blob/6cc3798978dddb4120d55d8130db3bb52e0ddcbe/src/substrate-lib/components/TxButton.js#L72

this has to be changed because we'd like to verify per tx in the backend

**Comment by mosonyi** [comment]
The backend server checks the tx hash from the block hash and account id.
I close this one.

**Comment by brenzi** [comment]
Your workaround is fine for now, but it doesn't resolve this issue really. I'd like to keep it open as I see it as technical debt

**Comment by anizeani** [comment]
so is it wished to send the tx hash to the backend? this shouldn't be a biggy..

**Comment by brenzi** [comment]
I'd prefer to work with txhash, but @mosonyi would need to change rhe backend accordingly

**Comment by brenzi** [comment]
wontfix
