### ISSUE TITLE
account selector should only show transferrable balance

### ISSUE THREAD

**Issue by brenzi** [integritee-network/crowdloan#52]
The current implementation shows the actual account balance (including reserved amounts). This can confuse people as they may think they can contribute more than they have actually available to transfer. So the contribution will fail

actually, it seems the code is correct. don't know why the balance isn't as expected:
https://github.com/integritee-network/crowdloan/blob/518546e68aa5e11bb8df0ed0f28f11b343d35e3c/src/AccountSelector.js#L124

**Comment by mosonyi** [comment]
I can confirm our app accepts any value of contribution, but later on, the verification will fail and the participant will be notified if there's a given email address.
I would handle this with high prio.

**Comment by brenzi** [comment]
even after #56  we still check for total balance, not transferrable balance.

**Comment by brenzi** [comment]
same same #53?

**Comment by brenzi** [comment]
also: show estimated fees and ensure that the max amount has room for fees
